version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Comercio_electronico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/Comercio_electronico
      JWT_SECRET: clave_super_secreta
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000/api
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  pgdata:
