version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"  # Tomará la URL de tu .env
      JWT_SECRET: "${JWT_SECRET}"
      NODE_ENV: "${NODE_ENV}"
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "5173:80"   # Puerto 80 del contenedor mapeado al 5173 del host
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://backend_app:3000/api"

volumes:
  # No se necesita volumen ya que no usamos contenedor DB local
