version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nombre_bd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - backend_net

  prisma-migrate:
    build: ./backend
    container_name: prisma_migrate
    command: ["npx", "prisma", "migrate", "deploy"]
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - backend_net

volumes:
  db_data:

networks:
  backend_net:
    driver: bridge
